	NDefines.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
	NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 512
	NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10
	NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 16384
	NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41
	NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 16384

	NDefines.NGraphics.CAMERA_OUTSIDE_MAP_DISTANCE_TOP = 100.0
	NDefines.NGraphics.CAMERA_OUTSIDE_MAP_DISTANCE_BOTTOM = 100.0
	NDefines.NGraphics.CAMERA_ZOOM_KEY_SCALE = 0.01
	NDefines.NGraphics.CAMERA_ZOOM_SPEED_DISTANCE_MULT = 25.0
	
	NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_X = 2058.0
	NDefines.NFrontend.CAMERA_MIN_HEIGHT = 30.0
	NDefines.NGraphics.MAP_COLOR_LERP_FACTOR = 0.2
	NDefines_Graphics.NGraphics.COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 0.8
	NDefines.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 0.9
	NDefines_Graphics.NGraphics.BORDER_WIDTH = 0.8
	NDefines_Graphics.NGraphics.GRADIENT_BORDERS_COUNTRY_CENTER_THICKNESS = 1
	NDefines.NGraphics.COUNTRY_EDGE_SOFTNESS = 0.45
	NDefines.NGraphics.COUNTRY_GRADIENT_POWER = 1.2
	
